name = "gozaddy"
main = "worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

[vars]
# Comma-separated list of allowed origins, or "*" for any.
ALLOWED_ORIGINS = "https://dascient.com,https://dascient.github.io,https://*.godaddysites.com,https://labs-15v.pages.dev"
# Optional rotation order:
MODEL_PREFS = "gpt-4.1-mini,gpt-4o-mini"

[[kv_namespaces]]
binding = "GOZADDY_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # fill in after creating the KV namespace
