name = "worldwide-intel-api"
main = "worker.js"
compatibility_date = "2025-09-01"

[[kv_namespaces]]
binding = "NEWS_KV"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[triggers]
crons = ["*/10 * * * *"]
         # set "true" if using dedicated endpoints
